# Generated by Django 6.0.4 on 2026-07-17 13:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Construcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('localizacao_pino', models.JSONField(default=list, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2)])),
            ],
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.JSONField(default=list, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2)])),
            ],
        ),
        migrations.CreateModel(
            name='ConstrucaoRegiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.JSONField(default=list, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2)])),
                ('tamanho', models.JSONField(default=list, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2)])),
                ('construcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regiao', to='mapa.construcao')),
            ],
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_fim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencia_final', to='mapa.referencia')),
                ('local_inicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencia_inicio', to='mapa.referencia')),
            ],
        ),
    ]
