# Generated by Django 6.1.1 on 2026-09-19 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0002_usuarioprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='Nome da construção', max_length=255)),
                ('descricao', models.TextField(blank=True, default='')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('construcao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='mapa.construcao')),
                ('referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='mapa.referencia')),
            ],
        ),
    ]
