# Generated by Django 6.1.1 on 2026-09-26 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0003_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='construcao',
            name='referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='construcoes', to='mapa.referencia'),
        ),
    ]
