# Generated by Django 6.1.1 on 2026-09-26 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0004_construcao_referencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='construcao',
            name='referencia',
        ),
        migrations.AddField(
            model_name='referencia',
            name='construcao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencias', to='mapa.construcao'),
        ),
    ]
